KS-18-4-made a problem with the parcel
ShvetsovaTatyana/KotlinSprint pull request #91
Opened 2024-12-11 18:53 UTC by ShvetsovaTatyana

2024-12-12 17:30 UTC, ievetrovdev requested changes

2024-12-12 17:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_18/task_4.kt
> +abstract class Package(val length: Double) {
Можно сделать более элегантно, не проставляя значений по умолчанию в базовом классе. Либо вообще отказаться от свойств в родителе.

2024-12-12 17:30 UTC, ievetrovdev commented on src/main/kotlin/lesson_18/task_4.kt
> +        val square: Double = width * height
можно использовать более короткую формулу без дополнительной переменной и сразу возвращать значение

2024-12-13 11:51 UTC, ShvetsovaTatyana commented on src/main/kotlin/lesson_18/task_4.kt
> +abstract class Package(val length: Double) {
а почему отказаться? нам же надо указать общее свойство для наследников в родителе

2024-12-13 12:55 UTC, ShvetsovaTatyana commented on src/main/kotlin/lesson_18/task_4.kt
> +abstract class Package(val length: Double) {
я может поняла, вдруг у нас будет какая-то коробка без значения длины ,например, круглая коробка и нам свойство длина получается не нужно, верно?

2024-12-13 19:34 UTC, ievetrovdev approved these changes

2024-12-13 20:49 UTC, merged